= Professionelle Softwareentwicklung: Pflichtabgabe 7
:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Abgabe

Die Abgabe erfolgt, indem Sie Ihre Lösung in Ihr GitHub Repository pushen. Bitte überprüfen Sie über die GitHub Webseite, dass dies funktioniert hat.

IMPORTANT: Die Frist für die Abgabe ist Freitag, der 10.7.2020 um 12:00 Uhr Ortszeit Düsseldorf.

== Testing

WARNING: Um die Aufgabe zu lösen, sollten Sie das Arbeitsblatt von Woche 12 bearbeitet haben. 

Diese Pflichtaufgabe wird sich mit Tests und insbesondere Mocking befassen.

=== Eine Dystopie 

Wir schreiben das Jahr 2025, seit 5 Jahren leben wir mit dem Corona Virus. Ein Impfstoff konnte nie entwickelt werden und es wurde festgestellt, dass der Großteil der Menschen selbst nach der Erkrankung nur wenige Monate lang immun ist. Wohl oder übel musste sich die Welt mit dem Virus arrangieren. In den USA wurde am Ende der zweiten Amtszeit von Präsident Trump ein Schnelltestgerät  entwickelt, welches rasenden Absatz hatte. In Deutschland wurde unter Bundeskanzler Spahn das Gesetz zur Seuchenkontrolle beschlossen, das den Umgang zwischen Menschen regelt. Schnelltestgeräte sind praktisch an jeder Ecke aufgestellt. Die Schnelltestgeräte geben QR Codes aus, die den freien Zugang zu Geschäften, etc. ermöglichen, es gilt aber weiterhin die Einhaltung des Mindestabstands und die Maskenpflicht. Positiv getestete Menschen müssen sich umgehend in Quarantäne begeben. Zuwiderhandlungen werden mit hohen Bußgeldern oder sogar Gefängnis bestraft. Glücklicherweise halten sich die meisten Bürger an die Verordnungen und so hat das Leben eine Art Normalzustand erreicht. Es gibt sogar wieder Präsenzveranstaltungen an der Uni. 

=== Die Software
An praktisch jedem Zugang zu einem Geschäft, öffentlichem Park, Restaurant, usw. sind Scanner aufgestellt, die den Zugang regeln. Es dürfen nur eine bestimmte Anzahl von Personen gleichzeitig in dem Bereich sein. Die Anzahl der Personen in einem Bereich hängt von den baulichen Bedingungen und der Nutzungsweise ab. Die Höchstpersonenzahl wird vom Amt für Seuchenschutz für jeden Bereich festgelegt. Es gibt immer eine Nutzungsreserve die freigehalten werden muss, damit zum Beispiel Angestellte, die in dem Bereich arbeiten noch den Bereich betreten dürfen. Die Nutzungsreserve wird von dem Betreiber des Bereich festgelegt. Ein Scanner an einem Zugang lässt "normale" Personen das Gebäude betreten, solange die Höchspersonenzahl minus der Nutzungsreserve nicht erreicht wurde. Angestellte können solange den Bereich betreten, bis die Höchstgrenze erreicht wurde. Sondernutzer (Polizei, Zoll, Feuerwehr, Rettungsdienst, THW) dürfen immer den Bereich betreten unabhängig davon, wieviele Personen im Bereich sind. Sondernutzer werden aber mitgezählt. Es werden ausschließlich Personen in den Bereich eingelassen, die einen negativen Schnelltest haben, der nicht älter ist als 5 Stunden ist. Versucht eine Person mit positivem KontrollSotwareTest den Bereich zu betreten, wird der Zugang blockiert und ein Alarm ausgelöst.

Die Scanner an den verschiedenen Zugängen kommunizieren über ein Netzwerk miteinander. Das Netzwerk wird nicht von Ihnen entwickelt, es stellt folgendes Interface bereit:

[source, java]
----
public interface Netzwerk {

    // Sendet eine Nachricht an alle anderen Zugangspunkte
    void broadcastMessage(Message message);
    
    // true <=> eine Nachricht ist vorhanden
    boolean readyToReceive();

    // Nächste Nachricht empfangen
    // Nur aufrufen, wenn eine Nachricht vorhanden ist
    Message receiveMessageBlocking();

}
----

Ihre Software muss mit der Hardware an den Zugangspunkten kommunizieren. Auch hier gibt es eine fertige Schnittstelle, die Sie verwenden müssen:

[source, java]
----
public interface Scanner {

    // true <=> eine Person ist am Kontrollsoftware
    boolean readyToProcessPerson();

    // Nur aufrufen, wenn eine Person da ist
    // true: Person will rein
    // false: Person will raus 
    boolean personWantsToEnter();

    // Nur aufrufen, wenn eine Person verlassen will 
    // Muss immer gestattet werden!
    void allowLeave();

    // Starte den Scanning Prozess
    // Nur aufrufen, wenn eine Person einteten will
    void scanCertificate();

    // Nur aufrufen, wenn das Zertifikat gescannt wurde
    // true <=> letzter KontrollSotwareTest ist negativ
    boolean covidNegativeCertificate();

    // Nur aufrufen, wenn das Zertifikat gescannt wurde
    // Zeitpunkt des Tests
    LocalDateTime certificateDate();

    // Status der Person (normal, angestellt, sonderrechte)
    // Nur aufrufen, wenn eine Person einteten will
    PersonCategory category();
        
    // Zugang gestatten      
    void allowAccess();

    // Zugang temporär verweigern (zu voll)
    void temporaryDenyAccess();

    // Alarm auslösen (positiv getestete Person)
    void sendAlert();

}
----

Ihre Aufgabe ist es die Kontrollsoftware für einen Kontrollsoftware zu entwerfen.

Beim Start bekommt das System die Höchstpersonenzahl, die Nutzungsreserve und die aktuelle Anzahl an Personen im Bereich übermittelt. Außerdem wird das System mit Zugang zum Netzwerk und dem Scanner versorgt. Diese Parameter werden alle dem Konstruktor übergeben. Sie dürfen weitere Parameter hinzufügen (vermutlich werden Sie das auch müssen).

IMPORTANT: Sie müssen sinnvolle Tests für jedes Feature schreiben, das Sie implementieren. Ersetzen Sie externe Systeme in Ihren Tests durch passende Stubs. Verwenden Sie Mockito bzw., falls es sich anbieten sollte, Lambda Ausdrücke. Vermutlich werden Sie auch Mocks benutzen müssen.  

Denken Sie daran, verschiedene Variationen und Grenzfälle der Eingabedaten zu prüfen. Ihre Tests müssen den gelernten Prinzipien entsprechen und nach dem AAA Muster strukturiert sein. Ihre Implementierung soll nach den Regeln und Prinzipien, die Sie kennengelernt haben entwickelt werden.  

Dokumentieren Sie ihr Vorgehen in der Datei link:DOKUMENTATION.adoc[`DOKUMENTATION.adoc`]. Ihre Dokumentaton muss es uns ermöglichen, Ihre Gedankengänge, Entscheidungen und Implementierung nachzuvollziehen. Wenn Sie Annahmen über das System treffen müssen diese dokumentiert werden.

NOTE: Wir ignorieren die Tatsache, dass in einem Netzwerk Latenzen oder Fehler auftreten können. *Diese Annahme ist vollkommener Unsinn!* Aber uns geht es hier um Testing, nicht um verteilte Systeme! 

**Hinweise zur Bewertung**

Das Lernziel der Aufgabe ist das Testing einer Anwendung, die aus mehreren Komponenten besteht. Sie sollen dabei Mockito anwenden. 

Achten Sie bei Ihren Tests besonders darauf, dass jeder KontrollSotwareTest nur einen Sachverhalt testet.

Bei der Implementierung ist uns wichtig, dass Sie den Code nicht zusammenhacken, sondern sich Mühe geben bei der Strukturierung und der Codequalität. Achten Sie auf konsistente Formatierung, sinnvolle Benennung, SLAP, etc. 



// =============================================================================== 

== Hinweise zur Abgabe

Der folgende Text stand in den vorhergehenden Abgaben oben und gilt auch weiterhin.

=== Strukturierung von Textabgaben

Sie sollten Ihre schriftlichen Ausarbeitungen, soweit verlangt, als https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc] formatieren. Die READMEs, die Sie in Ihren bisherigen Projekten finden konnten, sind auch allesamt mit AsciiDoc formatiert und daran können Sie sich orientieren. Github rendert AsciiDoc zu einer schönen Seite zusammen. AsciiDoc-Dateien erkennt man meistens an der Dateiendung `.adoc`.

AsciiDoc ist eine Markup-Formatierungssprache, die in reiner Textform mit jedem Editor geschrieben werden kann. Dafür sind prinzipiell keine Tools notwendig. Sie können aber dennoch ein paar Tools / Plugins in Ihre Editoren installieren, damit Sie ein wenig farbliche / technische Unterstützung beim Schreiben erhalten können. Für viele Editoren gibt es Plugins (https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[VS Code / VS Codium], https://marketplace.eclipse.org/content/asciidoctor-editor[für Eclipse], https://plugins.jetbrains.com/plugin/7391-asciidoc[IntelliJ], uvm.). Nutzen Sie was Ihnen am Besten gefällt.

==== Videos

Es gibt viele Anleitungen zur Verwendung AsciiDoc. Hier sind ein paar Ideen:

* Vor ein paar Jahren hat Jens einen Screencast erstellt. Die ersten Minuten sind aufschlussreich für die generelle Verwendung von AsciiDoc. Von uns verwendet aber niemand mehr den Editor Atom, weshalb die Hinweise zu den Plugins nicht mehr so hilfreich sind: https://www.youtube.com/watch?v=w9ZE-K5XBvc. Atom wurde von vielen EntwicklerInnen durch den Editor https://code.visualstudio.com/[VS Code] oder der freien Variante https://vscodium.com/[VS Codium] abgelöst.
* Diverse Screencasts finden sich auf Youtube. Die ersten Minuten dieses Talks geben auch einen guten Einblick: https://www.youtube.com/watch?v=MyhiD65qaUI


=== Rechtschreibung

Sie müssen sich an geltende Rechtschreibregeln halten. Sind Ihre schriftliche Abgaben nicht leserlich oder verständlich geschrieben, können wir diese Abgaben nicht als bestanden werten. Bitte achten Sie selbst also auf eine korrekte Orthographie und Grammatik.

Die Abgaben dürfen entweder in _deutscher_ oder _englischer_ Sprache verfasst werden.
